### ISSUE TITLE
Will the 4.8 profiles work with 4.9?

### ISSUE THREAD

**Issue by BaileyMillerSSI** [Kaouthia/Snapmaker-2#1]
I just got notified about an update to Cura but I don't want to break anything with the profiles. Have you updated to Cura 4.9 yet?

**Comment by Kaouthia** [comment]
I haven't tested them with 4.9 yet, but they should work just fine. Will check this weekend if I get the chance. :)

**Comment by BaileyMillerSSI** [comment]
By the way thanks again for creating these profiles. My A350 has been printing non-stop since I got it and these profiles look great.

While I have you can I ask a rookie question?
I just ordered [this filament](https://www.amazon.com/gp/product/B083JB4GDN/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) for a print I need and I realized it's PLA+ and these profiles are setup for base PLA. Will the only thing I need to tweak be the nozzle temp and maybe the bed when I use this filament or will it not work very well with these profiles?

**Comment by Kaouthia** [comment]
I'm going to close this one up, because it's not really a bug, haha. But feel free to take it to the discussion tab. :)
